spring.config.import=optional:file:.env[.properties]
spring.application.name=mix-arretado-backend

# Configuração do PostgreSQL / Supabase
#spring.datasource.url=jdbc:postgresql://${SUPABASE_HOST}:5432/postgres
spring.datasource.url=jdbc:postgresql://${SUPABASE_HOST}:5432/postgres?user=${SUPABASE_USER}&password=${SUPABASE_PASSWORD}
spring.datasource.username=${SUPABASE_USER}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativar inicializações específicas do H2
spring.jpa.defer-datasource-initialization=false